import disableAutofix from 'eslint-plugin-disable-autofix'
import globals from 'globals'
import html from '@html-eslint/eslint-plugin'
import htmlParser from '@html-eslint/parser'
import pluginJs from '@eslint/js'

export default [
  { ignores: ['dist', 'eslint.config.js', 'vite.config.js'] },

  // JS config
  {
    languageOptions: { globals: globals.browser },
    ...pluginJs.configs.recommended,
    rules: {
      eqeqeq: ['error', 'always'],
      quotes: ['warn', 'single'],
      camelcase: ['error', { ignoreImports: true, properties: 'never' }],
      complexity: ['error', 5],
      curly: ['error', 'multi-line'],
      'for-direction': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-imports': 'error',
      'no-invalid-regexp': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable': 'error',
      'no-unused-vars': 'error',
      'no-use-before-define': 'error',
      'no-console': 'warn',
      'no-undef': 'error',
      'no-redeclare': 'error',
      'no-shadow': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'default-case': 'error',
      'no-alert': 'warn',
      'no-bitwise': 'error',
      'no-empty-static-block': 'error',
      'no-eq-null': 'error',
      'no-extra-label': 'error',
      'no-label-var': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-undef-init': 'error',
      'no-lone-blocks': 'warn',
      'no-useless-assignment': 'warn',
      'require-atomic-updates': 'error',
      'no-else-return': 'error',
      'no-nested-ternary': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-rename': 'error',
      'operator-assignment': ['warn', 'always'],
      'require-await': 'error',
      'arrow-spacing': ['error', { before: true, after: true }],
      'no-empty-function': ['error', { allow: ['setters', 'constructors'] }],
      'sort-imports': [
        'error',
        {
          ignoreCase: false,
          ignoreDeclarationSort: false,
          ignoreMemberSort: false,
          memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
          allowSeparatedGroups: false,
        },
      ],
      'sort-vars': 'error',
      'vars-on-top': 'error',
    },
  },

  // HTML config
  {
    ...html.configs['flat/recommended'],
    files: ['**/*.html'],
    plugins: {
      '@html-eslint': html,
      'disable-autofix': disableAutofix,
    },
    rules: {
      '@html-eslint/require-attrs': [
        'error',
        {
          tag: 'img',
          attr: 'alt',
        },
        {
          tag: 'img',
          attr: 'src',
        },
        {
          tag: 'a',
          attr: 'href',
        },
      ],
      '@html-eslint/attrs-newline': 'off',
      '@html-eslint/no-restricted-attr-values': [
        'error',
        {
          attrPatterns: ['^class$'],
          attrValuePatterns: [
            '\\b(_{0,2})?(-{0,2})?([bB][oO][lL][dD]|[bB][oO][lL][dD][eE][rR]|[lL][iI][gG][hH]|[lL][iI][gG][hH][tT][eE][rR]|[nN][oO][rR][mM][aA][lL]|[iI][tT][aA][lL][iI][cC]|[oO][bB][lL][iI][qQ][uU][eE]|[uU][nN][dD][eE][rR][lL][iI][nN][eE]|[lL][iI][nN][eE]-[tT][hH][rR][oO][uU][gG][hH]|[oO][vV][eE][rR][lL][iI][nN][eE]|[wW][iI][dD][eE]|[nN][aA][rR][rR][oO][wW]|[tT][aA][lL][lL]|[sS][hH][oO][rR][tT]|[rR][eE][lL][aA][tT][iI][vV][eE]|[aA][bB][sS][oO][lL][uU][tT][eE]|[rR][eE][dD]|[bB][lL][uU][eE]|[gG][rR][eE][eE][nN]|[yY][eE][lL][lL][oO][wW]|[pP][uU][rR][pP][lL][eE]|[oO][rR][aA][nN][gG][eE]|[pP][iI][nN][kK]|[bB][lL][aA][cC][kK]|[wW][hH][iI][tT][eE]|[gG][rR][aA][yY]|[lL][iI][gG][hH][tT][gG][rR][aA][yY]|[dD][aA][rR][kK][gG][rR][aA][yY]|[bB][rR][oO][wW][nN]|[cC][yY][aA][nN]|[mM][aA][gG][eE][nN][tT][aA])(_{0,2})?(-{0,2})?\\b',
          ],
          message: 'One of the ClassName is in restricted list',
        },
        {
          attrPatterns: ['^class$'],
          attrValuePatterns: [
            '[a-zA-Z\\d]+(_{3,}|-{3,})',
            '(_|-)$',
            '[a-zA-Z\\d]*(_|-)$',
            '[a-zA-Z\\d][-]?[a-zA-Z\\d]+(_|-{2})[-a-zA-Z\\d]+(_|-{2})',
            '[a-zA-Z\\d]+(__)[-a-zA-Z]+(__)',
            '[^a-zA-Z\\d_\\-\\s\\{\\}\\/#]',
            '\\{\\{[-_]*\\}\\}',
            '\\{\\}|\\{\\{\\}\\}',
            '\\{[^\\}]*$',
            '(?<![a-zA-Z0-9\\}])\\}',
            '(?<!\\{)#',
            '(?<!\\{)\\/',
          ],
          message: 'Class pattern must match BEM',
        },
        {
          attrPatterns: ['^class$'],
          attrValuePatterns: ['[a-zA-Z]+--[a-zA-Z]+'],
          message: 'using wrong modificator syntaxis. instead _ you use --',
        },
        {
          attrPatterns: ['^id$'],
          attrValuePatterns: ['[^a-zA-Z\\d_\\-\\s\\{\\}]'],
          message: 'Incorrect ID pattern',
        },
      ],
      '@html-eslint/element-newline': [
        'error',
        {
          skip: ['p', 'span'],
        },
      ],
      '@html-eslint/no-extra-spacing-attrs': ['error', { disallowMissing: true }],
      '@html-eslint/no-multiple-empty-lines': ['error', { max: 1 }],
      '@html-eslint/no-target-blank': 'warn',
      '@html-eslint/no-duplicate-attrs': 'error',
      '@html-eslint/no-duplicate-id': 'error',
      '@html-eslint/no-inline-styles': 'warn',
      '@html-eslint/no-obsolete-tags': 'error',
      '@html-eslint/no-script-style-type': 'error',
      '@html-eslint/require-button-type': 'warn',
      '@html-eslint/require-closing-tags': 'warn',
      '@html-eslint/require-doctype': 'error',
      '@html-eslint/require-li-container': 'error',
      '@html-eslint/no-multiple-h1': 'error',
      '@html-eslint/no-skip-heading-levels': 'error',
      '@html-eslint/require-lang': 'warn',
      '@html-eslint/require-meta-charset': 'error',
      '@html-eslint/require-meta-description': 'error',
      '@html-eslint/require-title': 'error',
      '@html-eslint/require-img-alt': 'error',
      '@html-eslint/lowercase': 'error',
      '@html-eslint/no-positive-tabindex': 'error',
      '@html-eslint/no-non-scalable-viewport': 'warn',
      '@html-eslint/sort-attrs': 'off',
      'disable-autofix/@html-eslint/sort-attrs': [
        'warn',
        {
          priority: [
            'class',
            'id',
            'href',
            'action',
            'rel',
            'src',
            'alt',
            'target',
            'type',
            'srcset',
            'media',
            'name',
            'content',
            'accept',
            'width',
            'height',
            'style',
          ],
        },
      ],
    },
    languageOptions: {
      parser: htmlParser,
    },
  },
]
